### ISSUE TITLE
Integration with Unity IAP 2.2.5

### ISSUE THREAD

**Issue by gtino** [RevenueCat/purchases-unity#37]
Looks like the integration with Unity IAP 2.2.5 is broken and/or cannot be fixed by just following the instructions here: https://docs.revenuecat.com/v3.0/docs/unity#installation-with-unity-iap-side-by-side

After I setup the project as suggested, modifying the gradle file, I get the following:

Gradle Error: Colliding Attributes
The attribute meta-data#com.google.android.play.billingclient.version@value=3.0.1 in :com.android.billingclient.billing-no-service: collides with another value
(See the Console for details)

Attribute meta-data#com.google.android.play.billingclient.version@value value=(3.0.1) from [:billing-3.0.1:] AndroidManifest.xml:15:13-34 is also present at [:com.android.billingclient.billing-no-service:] AndroidManifest.xml:15:13-34 value=(2.0.3). Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:13:9-15:37 to override.

Among other 186+ errors that might just be cascading from this one.

Did something change with the latest Unity IAP and or Android billing libraries that made your guide for Unity IAP and RevenueCat integration obsolete?

**Comment by sanathkukkillaya** [comment]
Hi, I too am facing this issue. Looks like the RevenueCat billing library(v2.0.3) conflicts with the Unity billing library (v3.0.1). I am not sure if I should remove anything. Removing 2.0.3 might cause RevenueCat to fail, and removing 3.0.1 might cause issues, since Google is recommending to use v3 billing library. Any solution would help

**Comment by vegaro** [comment]
Releases of our SDK above 2.3.0 don't require extra steps when using alongside Unity IAP. This means that if someone is upgrading to 2.3.0 from a previous installation, they should remove this:

```
implementation ('com.revenuecat.purchases:purchases-hybrid-common:1.2.0') {
        exclude group: 'com.android.billingclient', module: 'billing'
}
```

Which were the previous instructions.

On top of that, if using a version of Unity IAP above 2.2.0, a version above 2.3.0 of our SDK needs to be used. In summary:

| Unity IAP | Compatible RevenueCat | Notes|
|---------|--------------------------|-------|
|<2.2.0     | <2.3.0                                 | Follow instructions in https://docs.revenuecat.com/v3.0/docs/unity#installation-with-unity-iap-side-by-side |
| 2.2.0+ |  2.3.0+ | No special instructions required, remove previous code added to gradle file if updating |

I will make sure the docs are updated to reflect this. I am sorry it wasn't clear at all. Let us know if you are still facing this issue or it gets fixed. Thanks!

**Comment by imurashka** [comment]
Hey @vegaro! Thanks for your reply! I have tried to follow instructions for both cases (Unity IAP <2.2.0 and 2.2.0+) but still have the same problem.
What I did step by step:
1. Created new unity project (unity verison is 2019.4.16 LTS)
2. Added Unity IAP (version 2.2.0) package
3. Downloaded latest RC from https://docs.revenuecat.com/docs/unity and imported it to project
4. Run dependency resolver (Assets -> External Dependency Manager -> Android Resolver -> Force Resole)
5. Start Android build
After that step I have more than hundred errors in console after 
` java.lang.RuntimeException: Duplicate class com.android.billingclient.BuildConfig found in modules classes.jar (:billing-3.0.1:) and classes.jar (:com.android.billingclient.billing-3.0.1:)`
There is test project with error - [RevenueCatTest.zip](https://github.com/RevenueCat/purchases-unity/files/5994422/RevenueCatTest.zip)
I will be very happe if you will check it and probably point on my mistake.

**Comment by vegaro** [comment]
Thanks for sending that over! I will look into it now

**Comment by vegaro** [comment]
I think I figured it out. As you pointed out, the implementation alongside Unity IAP was broken. We are truly sorry about that.

Please let me know if the following instructions fix the issues you're facing, just in case I am missing something:

### New instructions


If using RevenueCat alongside Unity IAP or other plugin that includes the Android BillingClient library you will be getting an error when compiling that warns about some BillingClient classes being duplicated.

The easiest way to remove the error would be to tell Gradle to not include the billingclient library that Unity IAP is already including.

In order to do that, make sure you have `Custom Main Gradle Template` selected in the Android Player Settings... That should create a `mainTemplate.gradle` inside the `Assets/Plugins/Android`.


![](https://files.readme.io/8925eda-Screen_Shot_2020-05-05_at_1.49.57_PM.png)

Modify the `mainTemplate.gradle` to include the following at the end of the dependencies block:

```groovy
dependencies {
     ...
    // ** ADD THIS **
    configurations.all {
        exclude group: 'com.android.billingclient', module: 'billing'
    }
}
```

**Comment by imurashka** [comment]
Hey @vegaro and thank you for the help. Very appreciated! I tried your solution and it works now :)

**Comment by vegaro** [comment]
That's great to hear! I will let our support team know and will update the docs. I am going to go ahead and close this issue. @gtino @sanathkukkillaya please let us know if the new instructions don't fix your issues, I believe they will

**Comment by ALI3NPANDA** [comment]
Hey @vegaro, I am facing this same issue again in unity 2020. I updated the unity In-App Purchase from 4.0.3 to 4.1.2.  Also, I tried the above solutions and still, the same error persists.

```
C:\Unity Games\Test project\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:15:13-34 Error:
	Attribute meta-data#com.google.android.play.billingclient.version@value value=(3.0.3) from [:billing-3.0.3:] AndroidManifest.xml:15:13-34
	is also present at [:GooglePlayBilling:] AndroidManifest.xml:15:13-34 value=(3.0.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:13:9-15:37 to override.
```
Even I tried this part to `add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:`
